services:

    agit.user:
        class: Agit\UserBundle\Service\UserService
        arguments: [@session, @security.token_storage, @security.encoder_factory, @doctrine.orm.entity_manager, @validator, @agit.validation]
