services:

    agit.user:
        class: Agit\UserBundle\Service\UserService
        arguments: [@security.context, @security.encoder_factory, @doctrine.orm.entity_manager, @agit.validation]

    # listening for capabilities
    agit.user.register.capability:
        private: true
        class: FixtureListener
        factory_service:  agit.pluggable.fixture.listener.factory
        factory_method:   create
        arguments: [AgitUserBundle:UserCapability, 1]
        tags: [{ name: kernel.event_listener, event: agit.pluggable, method: onRegistration }]

    # listening for roles
    agit.user.register.role:
        private: true
        class: FixtureListener
        factory_service:  agit.pluggable.fixture.listener.factory
        factory_method:   create
        arguments: [AgitUserBundle:UserRole, 2]
        tags: [{ name: kernel.event_listener, event: agit.pluggable, method: onRegistration }]

    # registering our own roles
    _agit.user.fixture.role.listener:
        class: Agit\UserBundle\EventListener\UserRoleFixtureData
        tags: [{ name: kernel.event_listener, event: AgitUserBundle:UserRole, method: onRegistration }]
