services:

    agit.user:
        class: Agit\UserBundle\Service\UserService
        arguments: [@session, @security.context, @security.encoder_factory, @doctrine.orm.entity_manager, @agit.validation]
